# username: wenay24905
# password: Senha123
database:
  drop_tables: false
  name: database.db
proxy: 'http://127.0.0.1:8118'
cookiejar: 'C:\Users\Kelvin\Downloads\cookies.undefined.txt'
throttle:
  enabled: true
  debug: true
  download_delay: 2
  concurrent_requests: 1
  concurrent_requests_per_domain: 1
market_configs:
  big_blue_market:
    enabled: true
    name: Big Blue Market
    url: http://zcqbitqnuukivywgsbl75advykjckmvzqo4dtlavvpb76ogsyjcnquyd.onion/
  white_house_market:
    enabled: false
    name: White House Market
    url: http://flkzk2qjqe2yo5etsb7klxjihgrj7bi54k3iscccvkk7xbkif6x5etad.onion/
  empire_market:
    enabled: false
    name: Empire Market
    url: hdzxqmipsdhj72frpkrplk6lofpwstmkr65tb53zm54yxnamg2suymid.onion
  icarus_market:
    enabled: false
    name: Icarus Market
    url: darknet3ysxpbjtvbtyqorzuq3bp4pk3vt4fuhqxz6h2bzj2kyjbisqd.onion