market_configs:
  empire_market:
    name: Empire Market
    url: http://hdzxqmipsdhj72frpkrplk6lofpwstmkr65tb53zm54yxnamg2suymid.onion/home/searchproducts/database
    # username: wenay24905
    # password: Senha123
    cookies:
      dcap: A81BC56DCC07C22B0E729B59E3A189147D631150CBC2D6F9260C0BA2625222405D98E2DBB618C6C0732E19DD82A65B31
      shop: khsnb639d5cgroam71cp6qt4d0qbj0g4