# username: wenay24905
# password: Senha123
database:
  drop_tables: false
market_configs:
  empire_market:
    enabled: true
    name: Empire Market
    url: http://hdzxqmipsdhj72frpkrplk6lofpwstmkr65tb53zm54yxnamg2suymid.onion/home/searchproducts/database
    cookies:
      dcap: A81BC56DCC07C22B0E729B59E3A18914C4A759420559A87E8C6FFEE3F418382F170D4F06778D4F634204F1132EC9495C
      shop: 2mgj4ngnupjvjapiia7l0v0m0u7m4rha
  icarus_market:
    enabled: false
    name: Icarus Market
    url: http://icarus5kuzorj3hz.onion/search/data/database/all/0/all/all/no/all/all/all/9999/all/all/all/all
    cookies:
      Icarus: n7565fu336b4b8q11kben3bdt4