# username: wenay24905
# password: Senha123
database:
  drop_tables: false
market_configs:
  empire_market:
    enabled: true
    name: Empire Market
    url: http://hdzxqmipsdhj72frpkrplk6lofpwstmkr65tb53zm54yxnamg2suymid.onion/home/searchproducts/database
    cookies:
      dcap: A81BC56DCC07C22B0E729B59E3A189148222AC885FE549FE7277EEE8F3206BAEE5FFF363F202CD14EE4B07C6BC4A7975
      shop: cfp9sgghkuoj4orh83q4f2p8pr514njv
  icarus_market:
    enabled: false
    name: Icarus Market
    url: http://icarus5kuzorj3hz.onion/search/data/database/all/0/all/all/no/all/all/all/9999/all/all/all/all
    cookies:
      Icarus: 49j7s2g26m2v9id9igcdgg3q96