# username: wenay24905
# password: Senha123
database:
  drop_tables: false
  name: database.sqlite
proxy: 'http://127.0.0.1:8118'
cookiejar: cookies.txt
market_configs:
  white_house_market:
    enabled: true
    name: White House Market
    url: flkzk2qjqe2yo5etsb7klxjihgrj7bi54k3iscccvkk7xbkif6x5etad.onion
  empire_market:
    enabled: false
    name: Empire Market
    url: hdzxqmipsdhj72frpkrplk6lofpwstmkr65tb53zm54yxnamg2suymid.onion
  icarus_market:
    enabled: false
    name: Icarus Market
    url: darknet3ysxpbjtvbtyqorzuq3bp4pk3vt4fuhqxz6h2bzj2kyjbisqd.onion